input {
  file {
    path => "/usr/share/logstash/ingest_data/*"
    start_position => "beginning"
    mode => "read"
    sincedb_path => "/usr/share/logstash/data/plugins/inputs/file/logstash-kafka-in.sincedb"
  }
}

filter {
}

output {
  kafka {
    bootstrap_servers => "${KAFKA_BOOTSTRAP_SERVERS}"
    topic_id => "${KAFKA_TOPIC}"
    codec => json
    security_protocol => "SSL"
    ssl_ca_cert => "/usr/share/logstash/certs/ca/ca.crt"
  }

  stdout {
    codec => json_lines
  }
}
