# https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html
input {
  kafka {
    bootstrap_servers => "${KAFKA_BOOTSTRAP_SERVERS}"
    topics => ["elk-docker-ssl"]
    auto_offset_reset => "earliest"
    auto_create_topics => "true"
    
    # SSL Configuration
    security_protocol => "SSL"
    ssl_truststore_location => "/usr/share/logstash/config/certs/ca/ca.p12"
    ssl_truststore_password => "${KAFKA_SSL_TRUSTSTORE_PASSWORD}"
    ssl_truststore_type => "PKCS12"
    
    ssl_keystore_location => "/usr/share/logstash/config/certs/kafka-broker-1/kafka-broker-1.p12"
    ssl_keystore_password => "${KAFKA_SSL_KEYSTORE_PASSWORD}"
    ssl_keystore_type => "PKCS12"
    ssl_key_password => "${KAFKA_SSL_KEY_PASSWORD}"
    
    ssl_endpoint_identification_algorithm => ""
  }
}

filter {
  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} \{name=%{WORD:container_name}\} %{GREEDYDATA:csv_data}" }
  }
}

output {
  elasticsearch {
    index => "logstash-%{+YYYY.MM.dd}"
    hosts=> "${ELASTIC_HOSTS}"
    user=> "${ELASTIC_USER}"
    password=> "${ELASTIC_PASSWORD}"
    cacert=> "certs/ca/ca.crt"
  }
}
