input {
  kafka {
    bootstrap_servers => "${KAFKA_BOOTSTRAP_SERVERS}"
    topics => ["${KAFKA_TOPIC}"]
    auto_offset_reset => "earliest"
    codec => json
    security_protocol => "SSL"
    ssl_ca_cert => "/usr/share/logstash/certs/ca/ca.crt"
  }
}

filter {
}

output {
  elasticsearch {
    index => "kafka-demo-%{+YYYY.MM.dd}"
    hosts => "${ELASTIC_HOSTS}"
    user => "${ELASTIC_USER}"
    password => "${ELASTIC_PASSWORD}"
    ssl_certificate_authorities => "certs/ca/ca.crt"
  }

  stdout {
    codec => json_lines
  }
}
