# Logstash Input Configuration for SSL Kafka Cluster
# This configuration reads files from the ingest_data directory and sends them to the SSL-enabled Kafka cluster

input {
  file {
    #https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html
    #default is TAIL which assumes more data will come into the file.
    #change to mode => "read" if the file is a complete file. by default, the file will be removed once reading is complete -- backup your files if you need them.
    mode => "tail"
    path => "/usr/share/logstash/ingest_data/*"
  }
}

filter {
  csv {
    separator => ","
    autodetect_column_names => true
  }
}

# https://www.elastic.co/guide/en/logstash/current/plugins-outputs-kafka.html
output {
  kafka {
    bootstrap_servers => "${KAFKA_BOOTSTRAP_SERVERS}"
    topic_id => "elk-docker-ssl"
    
    # SSL Configuration
    security_protocol => "SSL"
    ssl_truststore_location => "/usr/share/logstash/config/certs/ca/ca.p12"
    ssl_truststore_password => "${KAFKA_SSL_TRUSTSTORE_PASSWORD}"
    ssl_truststore_type => "PKCS12"
    
    ssl_keystore_location => "/usr/share/logstash/config/certs/kafka-broker-1/kafka-broker-1.p12"
    ssl_keystore_password => "${KAFKA_SSL_KEYSTORE_PASSWORD}"
    ssl_keystore_type => "PKCS12"
    ssl_key_password => "${KAFKA_SSL_KEY_PASSWORD}"
    
    ssl_endpoint_identification_algorithm => ""
  }
}
